#activity code:KL/EP-19/A-004
#platform:python 3.10.7
#author:M.Rishibha
#role:software engineer.apsilon
#date:03.10.2022

#Q2. def f1():
 #port=5690
#f1()
#print(port)
#a. 5690
#b. None
#c. NameError

'''port is in a function print
   'prot' is in out of the function so name error found'''
